# Generated by Django 3.1.7 on 2021-03-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawaimodel',
            name='tmt_cpns',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
