# Generated by Django 3.1.7 on 2021-07-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawaimodel',
            name='tgllahir',
            field=models.DateField(blank=True, default='1990-01-01', null=True),
        ),
    ]
