# Generated by Django 3.1.7 on 2021-04-23 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golonganhistorymodel',
            name='dokumen',
            field=models.FileField(blank=True, null=True, upload_to='upload/skpangkat/', verbose_name='Dokumen'),
        ),
        migrations.AlterField(
            model_name='golonganhistorymodel',
            name='nama',
            field=models.ForeignKey(blank=True, default=24, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.golonganmodel', verbose_name='Nama Golongan'),
        ),
        migrations.AlterField(
            model_name='golonganhistorymodel',
            name='nip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='golonganhistorymodel',
            name='nomor_sk',
            field=models.CharField(blank=True, default='S-10225/BKD-2.2/', max_length=150, null=True, verbose_name='Nomor SK'),
        ),
        migrations.AlterField(
            model_name='golonganhistorymodel',
            name='tanggal',
            field=models.DateField(blank=True, default=1998, null=True, verbose_name='Tanggal'),
        ),
    ]
