# Generated by Django 3.1.7 on 2021-07-27 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golonganhistorymodel',
            name='dokumen',
            field=models.FileField(blank=True, null=True, upload_to='upload/berkas/'),
        ),
        migrations.AlterField(
            model_name='golonganhistorymodel',
            name='mk_bulan',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='golonganhistorymodel',
            name='mk_tahun',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='golonganhistorymodel',
            name='nama',
            field=models.ForeignKey(blank=True, default=24, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.golonganmodel'),
        ),
        migrations.AlterField(
            model_name='golonganhistorymodel',
            name='nomor_sk',
            field=models.CharField(blank=True, default='S-10225/BKD-2.2/', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='golonganhistorymodel',
            name='tanggal',
            field=models.DateField(blank=True, default=1998, null=True),
        ),
        migrations.AlterField(
            model_name='golonganhistorymodel',
            name='tglpenetapan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
