# Generated by Django 3.1 on 2021-03-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golonganhistorymodel',
            name='mk_bulan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='golonganhistorymodel',
            name='mk_tahun',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
