# Generated by Django 3.1.7 on 2021-03-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golonganhistorymodel',
            name='mk_bulan',
        ),
        migrations.RemoveField(
            model_name='golonganhistorymodel',
            name='mk_tahun',
        ),
        migrations.AddField(
            model_name='pegawaimodel',
            name='mk_bulan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pegawaimodel',
            name='mk_tahun',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
