# Generated by Django 3.1.7 on 2021-03-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akunmodel',
            name='pegawai',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
