# Generated by Django 3.1.7 on 2021-07-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawaimodel',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pegawaimodel',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
