# Generated by Django 3.1.7 on 2021-04-29 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_auto_20210423_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosesberkalamodel',
            name='gaji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.gajimodel'),
        ),
        migrations.AddField(
            model_name='prosesberkalamodel',
            name='jabatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.jabatanmodel'),
        ),
        migrations.AddField(
            model_name='prosesberkalamodel',
            name='mk_bulan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prosesberkalamodel',
            name='mk_tahun',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
