# Generated by Django 3.1.7 on 2021-07-16 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_auto_20210709_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominatifTundaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_tahun', models.IntegerField(blank=True, null=True)),
                ('mk_bulan', models.IntegerField(blank=True, null=True)),
                ('mkb_tahun', models.IntegerField(blank=True, null=True)),
                ('mkb_bulan', models.IntegerField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('tmt_kgb', models.DateField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, default='-', max_length=20, null=True)),
                ('gaji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.gajimodel')),
                ('golongan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.golonganmodel')),
                ('jabatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.jabatanmodel')),
                ('opd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.opdmodel')),
                ('pegawai', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.pegawaimodel')),
            ],
        ),
    ]
