# Generated by Django 3.1 on 2021-03-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_auto_20210323_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawaimodel',
            name='mk_bulan',
        ),
        migrations.RemoveField(
            model_name='pegawaimodel',
            name='mk_tahun',
        ),
    ]
