# Generated by Django 3.1.7 on 2021-07-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_auto_20210727_0641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golonganmodel',
            options={'managed': (True,)},
        ),
    ]
