# Generated by Django 3.1.7 on 2021-07-27 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0003_auto_20210727_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominatiftundamodel',
            name='keterangan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nominatiftundamodel',
            name='opd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.opdmodel', verbose_name='Unit Kerja'),
        ),
        migrations.AlterField(
            model_name='nominatiftundamodel',
            name='pegawai',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.pegawaimodel', verbose_name='Nama'),
        ),
    ]
