# Generated by Django 3.1.7 on 2021-07-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0003_auto_20210706_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawaimodel',
            name='pddk_terakhir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
