# Generated by Django 3.1.7 on 2021-03-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0003_auto_20210324_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golonganhistorymodel',
            name='mk_bulan',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='golonganhistorymodel',
            name='mk_tahun',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jabatanmodel',
            name='jenis',
            field=models.CharField(choices=[('struktural', 'Struktural'), ('jfu', 'Fungsional Umum'), ('jft1', 'Ahli Pertma'), ('jft2', 'Ahli Muda'), ('jft3', 'Ahli Madya'), ('jft4', 'Ahli Utama'), ('jft5', 'Pelaksana Pemula'), ('jft6', 'Pelaksana'), ('jft7', 'Ahli Utama')], default='jfu', max_length=30),
        ),
    ]
