# Generated by Django 3.1.7 on 2021-05-24 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0003_auto_20210429_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominatifxModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_tahun', models.IntegerField(blank=True, null=True)),
                ('mk_bulan', models.IntegerField(blank=True, null=True)),
                ('mkb_tahun', models.IntegerField(blank=True, null=True)),
                ('mkb_bulan', models.IntegerField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('tmt_kgb', models.DateField(blank=True, null=True)),
                ('bahan', models.CharField(blank=True, choices=[('l', 'Lengkap'), ('tl', 'Tidak Lengkap')], max_length=20)),
                ('gaji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.gajimodel')),
                ('jabatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.jabatanmodel')),
                ('pegawai', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.pegawaimodel')),
            ],
        ),
    ]
