# Generated by Django 3.1.7 on 2021-07-06 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0004_pegawaimodel_pddk_terakhir'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawaimodel',
            name='tmt_pns',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
