# Generated by Django 3.2.5 on 2021-07-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0004_auto_20210727_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominatiftundamodel',
            name='tmt_kgb',
            field=models.DateField(blank=True, null=True, verbose_name='TMT KGB'),
        ),
    ]
