# Generated by Django 3.1.7 on 2021-06-15 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0005_nominatifxmodels_golongan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawaimodel',
            name='nominasi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prosesberkalamodel',
            name='pegawai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.pegawaimodel'),
        ),
    ]
