# Generated by Django 3.1.7 on 2021-06-17 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0006_auto_20210615_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominatifxmodels',
            name='opd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.opdmodel'),
        ),
    ]
