# Generated by Django 3.1.7 on 2021-06-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0007_nominatifxmodels_opd'),
    ]

    operations = [
        migrations.AddField(
            model_name='golonganhistorymodel',
            name='dasarnominatif',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
