# Generated by Django 3.1.7 on 2021-07-01 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0009_nominatifselesaimodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosesberkalamodel',
            name='golongan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.golonganmodel'),
        ),
        migrations.AddField(
            model_name='prosesberkalamodel',
            name='mkb_bulan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prosesberkalamodel',
            name='mkb_tahun',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prosesberkalamodel',
            name='opd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.opdmodel'),
        ),
        migrations.AddField(
            model_name='prosesberkalamodel',
            name='tmt_kgb',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prosesberkalamodel',
            name='status',
            field=models.CharField(blank=True, choices=[('selesai', 'Selesai'), ('tertunda', 'Tertunda'), ('proses', 'Proses'), ('nominatif', 'Nominatif')], default='nominatif', max_length=20),
        ),
    ]
