# Generated by Django 3.1.7 on 2021-07-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0010_auto_20210701_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golonganmodel',
            options={'ordering': ['nama']},
        ),
    ]
