# Generated by Django 3.1.7 on 2021-07-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0011_auto_20210701_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golonganmodel',
            options={'managed': True},
        ),
    ]
